mod speedtest;
mod distance;

extern crate hyper;
extern crate xml;
extern crate time;

#[macro_use]
extern crate log;
extern crate env_logger;

#[macro_use]
extern crate clap;

use clap::{App};

#[allow(dead_code)]
fn main() {
    env_logger::init().unwrap();
    let matches = App::new("speedtest-rs")
                    .version(&crate_version!()[..])
                    .about("Command line interface for testing internet bandwidth using speedtest.net.")
                    .args_from_usage(
                        "--bytes 'Display values in bytes instead of bits. Does not affect the image generated by --share'
                        --share 'Generate and provide a URL to the speedtest.net share results image'
                        --simple 'Suppress verbose output, only show basic information'
                        --list 'Display a list of speedtest.net servers sorted by distance'
                        --server [SERVER] 'Specify a server ID to test against'
                        --mini [MINI] 'URL of the Speedtest Mini server'
                        --source [SOURCE] 'Source IP address to bind to'
                        --timeout [TIMEOUT] 'HTTP timeout in seconds. Default 10'"
                    )
                    .get_matches();
    info!("Starting up...");
    speedtest::run_speedtest();
}
