extern crate speedtest_rs;

#[macro_use]
extern crate log;
extern crate env_logger;

#[macro_use]
extern crate clap;

use clap::App;
// use speedtest_rs::speedtest::run_speedtest;

#[allow(dead_code)]
fn main() {
    env_logger::init().unwrap();
    let matches = App::new("speedtest-rs")
                      .version(&crate_version!()[..])
                      .about("Command line interface for testing internet bandwidth using \
                              speedtest.net.")
                      .args_from_usage("--bytes 'Display values in bytes instead of bits. Does                                    not affect the image generated by --share'
                                        --list \
                                        'Display a list of speedtest.net servers sorted by \
                                        distance'")
                      .get_matches();

}
